name: Sincronizar Repositorio Completo a Google Docs

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar librerías oficiales de Google
        run: |
          pip install google-api-python-client google-auth

      - name: Ejecutar script de sincronización en Python
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          FOLDER_ID: "16h3KIgT3XeiAbt6U4r3OV5Yao0RTw-zC"
          DOCUMENT_NAME: "REPOSITORIOS-GITHUB 2026"
        run: |
          python sincronizar.py
